ALTER TABLE users
  ADD COLUMN IF NOT EXISTS max_salary INTEGER,
  ADD COLUMN IF NOT EXISTS salary_currency VARCHAR(10),
  ADD COLUMN IF NOT EXISTS country VARCHAR(10),
  ADD COLUMN IF NOT EXISTS location TEXT,
  ADD COLUMN IF NOT EXISTS work_types JSONB,
  ADD COLUMN IF NOT EXISTS work_modes JSONB;
